name: Lua CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Installs and runs Luacheck
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck
        /home/runner/.luarocks/bin/luacheck . --no-color -q

    - name: Update Build Date
      run: sed -i "s/@build-time@/`date +%Y%m%d%H%M%S`/" WeakAuras/Init.lua

    - name: Create Retail Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z;
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    - uses: actions/upload-artifact@master
      with:
        name: Release Build
        path: .release/

    - name: Create Classic Package
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z -g 1.13.2 -m .pkgmeta-classic -w 24944;
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    - uses: actions/upload-artifact@master
      with:
        name: Classic Build
        path: .release/
